#!/bin/bash

# Advanced Firewall Configuration Script
# Supports both UFW and IPTABLES
# Usage: sudo bash firewall-config.sh [ufw|iptables]

set -euo pipefail

# Configuration
FIREWALL_TYPE=${1:-"ufw"}
SSH_PORT=${SSH_PORT:-2222}
ALLOWED_IPS_FILE="/etc/firewall/allowed-ips.txt"
BLOCKED_IPS_FILE="/etc/firewall/blocked-ips.txt"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Log file
LOG_FILE="/var/log/firewall-setup.log"

# Function to log messages
log() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')] $1${NC}" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1${NC}" | tee -a "$LOG_FILE"
    exit 1
}

warning() {
    echo -e "${YELLOW}[$(date '+%Y-%m-%d %H:%M:%S')] WARNING: $1${NC}" | tee -a "$LOG_FILE"
}

info() {
    echo -e "${BLUE}[$(date '+%Y-%m-%d %H:%M:%S')] INFO: $1${NC}" | tee -a "$LOG_FILE"
}

# Check root privileges
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root"
fi

# Create necessary directories
mkdir -p /etc/firewall

# Function to load IP lists
load_ip_lists() {
    # Create default allowed IPs file
    if [ ! -f "$ALLOWED_IPS_FILE" ]; then
        cat > "$ALLOWED_IPS_FILE" << EOF
# Allowed IPs for SSH access
# One IP per line
192.168.1.0/24
10.0.0.0/8
EOF
    fi

    # Create default blocked IPs file
    if [ ! -f "$BLOCKED_IPS_FILE" ]; then
        cat > "$BLOCKED_IPS_FILE" << EOF
# Blocked IPs (known malicious IPs)
# One IP per line
EOF
    fi
}

# Function to install and configure UFW
setup_ufw() {
    log "Setting up UFW (Uncomplicated Firewall)..."

    # Install UFW if not present
    if ! command -v ufw &> /dev/null; then
        apt-get update && apt-get install -y ufw
    fi

    # Reset existing rules
    ufw --force reset

    # Set default policies
    ufw default deny incoming
    ufw default deny routed
    ufw default allow outgoing

    # Allow loopback
    ufw allow in on lo

    # Allow essential services with rate limiting

    # SSH with rate limiting and IP whitelist
    if [ -f "$ALLOWED_IPS_FILE" ]; then
        while IFS= read -r ip; do
            if [[ ! "$ip" =~ ^# ]] && [ ! -z "$ip" ]; then
                ufw allow from "$ip" to any port "$SSH_PORT" proto tcp
                info "Allowed SSH access from $ip"
            fi
        done < "$ALLOWED_IPS_FILE"
    fi

    # Rate limiting for SSH
    ufw limit "$SSH_PORT"/tcp

    # HTTP/HTTPS
    ufw allow 80/tcp comment 'HTTP'
    ufw allow 443/tcp comment 'HTTPS'

    # DNS (if server is DNS server)
    ufw allow 53/tcp comment 'DNS TCP'
    ufw allow 53/udp comment 'DNS UDP'

    # Email services (if applicable)
    # ufw allow 25/tcp comment 'SMTP'
    # ufw allow 587/tcp comment 'SMTP Submission'
    # ufw allow 993/tcp comment 'IMAPS'
    # ufw allow 995/tcp comment 'POP3S'

    # Block IPs from blocked list
    if [ -f "$BLOCKED_IPS_FILE" ]; then
        while IFS= read -r ip; do
            if [[ ! "$ip" =~ ^# ]] && [ ! -z "$ip" ]; then
                ufw deny from "$ip"
                warning "Blocked IP: $ip"
            fi
        done < "$BLOCKED_IPS_FILE"
    fi

    # Additional security rules

    # Block common attack vectors
    ufw deny 23/tcp comment 'Block Telnet'
    ufw deny 135/tcp comment 'Block RPC'
    ufw deny 139/tcp comment 'Block NetBIOS'
    ufw deny 445/tcp comment 'Block SMB'
    ufw deny 3389/tcp comment 'Block RDP'

    # Limit connection attempts
    ufw deny 137:139/udp comment 'Block NetBIOS UDP'
    ufw deny 1433:1434/tcp comment 'Block MSSQL'
    ufw deny 3306/tcp comment 'Block MySQL from external'

    # Enable logging
    ufw logging on
    ufw logging medium

    # Enable firewall
    ufw --force enable

    # Show status
    ufw status verbose

    log "UFW configuration completed successfully!"
}

# Function to setup IPTABLES
setup_iptables() {
    log "Setting up IPTABLES..."

    # Install iptables-persistent if not present
    if ! command -v iptables-save &> /dev/null; then
        apt-get update && apt-get install -y iptables-persistent
    fi

    # Create iptables rules file
    cat > /etc/iptables/rules.v4 << 'EOF'
# IPTABLES Configuration
# Generated by firewall-config.sh

*filter

# Default policies
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]

# Custom chains
:LOGGING - [0:0]
:SCAN - [0:0]

# Allow loopback
-A INPUT -i lo -j ACCEPT

# Allow established and related connections
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Drop invalid packets
-A INPUT -m conntrack --ctstate INVALID -j DROP

# Block common scans
-A INPUT -p tcp --tcp-flags ALL NONE -j SCAN
-A INPUT -p tcp --tcp-flags ALL ALL -j SCAN
-A INPUT -p tcp --tcp-flags ALL FIN,URG,PSH -j SCAN
-A INPUT -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j SCAN
-A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -j SCAN
-A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -j SCAN
-A SCAN -j LOG --log-prefix "iptables-scan: " --log-level 4
-A SCAN -j DROP

# Rate limiting
-A INPUT -p tcp --dport 22 -m recent --name sshbf --rttl --rcheck --hitcount 3 --seconds 10 -j DROP
-A INPUT -p tcp --dport 22 -m recent --name sshbf --rttl --set

# Prevent SYN flood
-A INPUT -p tcp --syn -m limit --limit 1/s --limit-burst 3 -j ACCEPT
-A INPUT -p tcp --syn -j DROP

# Prevent ping flood
-A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
-A INPUT -p icmp --icmp-type echo-request -j DROP

EOF

    # Add SSH rules
    if [ -f "$ALLOWED_IPS_FILE" ]; then
        while IFS= read -r ip; do
            if [[ ! "$ip" =~ ^# ]] && [ ! -z "$ip" ]; then
                echo "-A INPUT -p tcp -s $ip --dport $SSH_PORT -j ACCEPT # SSH from $ip" >> /etc/iptables/rules.v4
                info "Added SSH rule for $ip"
            fi
        done < "$ALLOWED_IPS_FILE"
    fi

    # Add blocked IPs
    if [ -f "$BLOCKED_IPS_FILE" ]; then
        while IFS= read -r ip; do
            if [[ ! "$ip" =~ ^# ]] && [ ! -z "$ip" ]; then
                echo "-A INPUT -s $ip -j DROP # Blocked IP" >> /etc/iptables/rules.v4
                warning "Added block rule for $ip"
            fi
        done < "$BLOCKED_IPS_FILE"
    fi

    cat >> /etc/iptables/rules.v4 << EOF

# SSH (with rate limiting)
-A INPUT -p tcp --dport $SSH_PORT -m conntrack --ctstate NEW -m recent --set
-A INPUT -p tcp --dport $SSH_PORT -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 4 -j DROP
-A INPUT -p tcp --dport $SSH_PORT -m conntrack --ctstate NEW -j ACCEPT

# Web services
-A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT # HTTP
-A INPUT -p tcp --dport 443 -m conntrack --ctstate NEW -j ACCEPT # HTTPS

# DNS (if server is DNS server)
-A INPUT -p udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT # DNS UDP
-A INPUT -p tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT # DNS TCP

# Logging
-A INPUT -j LOGGING
-A LOGGING -j LOG --log-prefix "iptables-drop: " --log-level 4
-A LOGGING -j DROP

COMMIT
EOF

    # Create IPv6 rules file
    cat > /etc/iptables/rules.v6 << 'EOF'
*filter

:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]

# Allow loopback
-A INPUT -i lo -j ACCEPT

# Allow established and related
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# ICMPv6
-A INPUT -p icmpv6 -j ACCEPT

# SSH
-A INPUT -p tcp --dport 2222 -m conntrack --ctstate NEW -j ACCEPT

# Web services
-A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT
-A INPUT -p tcp --dport 443 -m conntrack --ctstate NEW -j ACCEPT

COMMIT
EOF

    # Apply rules
    iptables-restore < /etc/iptables/rules.v4
    ip6tables-restore < /etc/iptables/rules.v6

    # Save rules
    iptables-save > /etc/iptables/rules.v4
    ip6tables-save > /etc/iptables/rules.v6

    # Show current rules
    info "Current IPTABLES rules:"
    iptables -L -n -v

    log "IPTABLES configuration completed successfully!"
}

# Function to setup fail2ban integration
setup_fail2ban_integration() {
    log "Configuring fail2ban integration..."

    cat > /etc/fail2ban/jail.local << EOF
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
backend = systemd
usedns = warn
destemail = admin@yourdomain.com
sendername = Fail2Ban-Server
sender = fail2ban@yourdomain.com
mta = sendmail
protocol = tcp
chain = INPUT
port = 0:65535
fail2ban_agent = Fail2Ban/%(fail2ban_version)s

[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 86400
findtime = 600

[nginx-http-auth]
enabled = true
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 3

[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 10
findtime = 600

[nginx-noscript]
enabled = true
port = http,https
filter = nginx-noscript
logpath = /var/log/nginx/access.log
maxretry = 6
findtime = 600

[nginx-badbots]
enabled = true
port = http,https
filter = nginx-badbots
logpath = /var/log/nginx/access.log
maxretry = 2
findtime = 600

[postfix]
enabled = true
port = smtp,ssmtp
filter = postfix
logpath = /var/log/mail.log

[dovecot]
enabled = true
port = pop3,pop3s,imap,imaps
filter = dovecot
logpath = /var/log/mail.log
EOF

    systemctl restart fail2ban

    log "Fail2ban integration configured successfully!"
}

# Function to create monitoring script
create_monitoring_script() {
    log "Creating firewall monitoring script..."

    cat > /usr/local/bin/firewall-monitor.sh << 'EOF'
#!/bin/bash

# Firewall Monitoring Script

LOG_FILE="/var/log/firewall-monitor.log"
DATE=$(date '+%Y-%m-%d %H:%M:%S')

log_event() {
    echo "[$DATE] $1" >> $LOG_FILE
}

# Check firewall status
check_firewall() {
    if command -v ufw &> /dev/null; then
        if ! ufw status | grep -q "Status: active"; then
            log_event "CRITICAL: UFW firewall is not active!"
            # Attempt to restart
            ufw --force enable
        fi
    fi

    # Check for blocked IPs count
    BLOCKED_COUNT=$(iptables -L -n | grep -c "DROP")
    log_event "INFO: Currently blocking $BLOCKED_COUNT rules"

    # Check for recent attacks
    RECENT_ATTACKS=$(grep "iptables-scan\|iptables-drop" /var/log/kern.log | grep "$(date '+%b %d')" | wc -l)
    if [ $RECENT_ATTACKS -gt 100 ]; then
        log_event "WARNING: High number of attacks detected: $RECENT_ATTACKS"
    fi

    # Check fail2ban status
    if ! systemctl is-active --quiet fail2ban; then
        log_event "CRITICAL: Fail2ban is not running!"
        systemctl restart fail2ban
    fi

    # Check disk space for logs
    LOG_USAGE=$(df -h /var/log | awk 'NR==2 {print $5}' | sed 's/%//')
    if [ $LOG_USAGE -gt 85 ]; then
        log_event "WARNING: Log directory usage is at ${LOG_USAGE}%"
    fi
}

# Generate daily report
generate_report() {
    REPORT_FILE="/var/log/daily-firewall-report-$(date +%Y%m%d).txt"

    cat > "$REPORT_FILE" << EOF
Daily Firewall Report - $(date)
=================================

Blocked IPs Today:
$(grep "$(date '+%b %d')" /var/log/kern.log | grep "iptables-drop" | awk '{print $10}' | sort | uniq -c | sort -nr | head -10)

Top Attack Types Today:
$(grep "$(date '+%b %d')" /var/log/kern.log | grep "iptables-" | awk '{print $11}' | sort | uniq -c | sort -nr)

Fail2ban Bans Today:
$(grep "$(date '+%b %d')" /var/log/fail2ban.log | grep "Ban " | wc -l)

Current Active Rules:
$(iptables -L -n | grep -E "^[A-Z].*ACCEPT|DROP|REJECT" | wc -l)
EOF

    log_event "Daily report generated: $REPORT_FILE"
}

# Run checks
check_firewall
generate_report
EOF

    chmod +x /usr/local/bin/firewall-monitor.sh

    # Add to crontab
    (crontab -l 2>/dev/null; echo "*/10 * * * * /usr/local/bin/firewall-monitor.sh") | crontab -

    log "Firewall monitoring script created and scheduled!"
}

# Function to create IP management scripts
create_ip_management_scripts() {
    log "Creating IP management scripts..."

    # Script to add allowed IP
    cat > /usr/local/bin/allow-ip.sh << 'EOF'
#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <IP_ADDRESS> [COMMENT]"
    echo "Example: $0 192.168.1.100 'Office IP'"
    exit 1
fi

IP=$1
COMMENT=${2:-"Manual addition"}

# Validate IP format
if [[ ! $IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    echo "Invalid IP address format"
    exit 1
fi

# Add to allowed IPs file
echo "# $COMMENT" >> /etc/firewall/allowed-ips.txt
echo "$IP" >> /etc/firewall/allowed-ips.txt

# Update firewall if using UFW
if command -v ufw &> /dev/null; then
    ufw allow from "$IP" to any port 2222 proto tcp
    echo "Added $IP to UFW rules"
fi

# Update IPTABLES if present
if [ -f /etc/iptables/rules.v4 ]; then
    iptables -I INPUT -p tcp -s "$IP" --dport 2222 -j ACCEPT
    iptables-save > /etc/iptables/rules.v4
    echo "Added $IP to IPTABLES rules"
fi

echo "IP $IP has been added to allowed list"
EOF

    # Script to block IP
    cat > /usr/local/bin/block-ip.sh << 'EOF'
#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <IP_ADDRESS> [REASON]"
    echo "Example: $0 1.2.3.4 'Failed login attempts'"
    exit 1
fi

IP=$1
REASON=${2:-"Manual block"}

# Validate IP format
if [[ ! $IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    echo "Invalid IP address format"
    exit 1
fi

# Add to blocked IPs file
echo "# Blocked on $(date) - $REASON" >> /etc/firewall/blocked-ips.txt
echo "$IP" >> /etc/firewall/blocked-ips.txt

# Update firewall if using UFW
if command -v ufw &> /dev/null; then
    ufw deny from "$IP"
    echo "Added $IP to UFW deny rules"
fi

# Update IPTABLES if present
if [ -f /etc/iptables/rules.v4 ]; then
    iptables -I INPUT -s "$IP" -j DROP
    iptables-save > /etc/iptables/rules.v4
    echo "Added $IP to IPTABLES drop rules"
fi

echo "IP $IP has been blocked. Reason: $REASON"
EOF

    chmod +x /usr/local/bin/allow-ip.sh
    chmod +x /usr/local/bin/block-ip.sh

    log "IP management scripts created successfully!"
}

# Main execution
main() {
    log "Starting firewall configuration..."
    log "Firewall type: $FIREWALL_TYPE"
    log "SSH Port: $SSH_PORT"

    # Load IP lists
    load_ip_lists

    # Setup firewall based on type
    case $FIREWALL_TYPE in
        "ufw")
            setup_ufw
            ;;
        "iptables")
            setup_iptables
            ;;
        *)
            error "Invalid firewall type. Use 'ufw' or 'iptables'"
            ;;
    esac

    # Setup additional components
    setup_fail2ban_integration
    create_monitoring_script
    create_ip_management_scripts

    # Generate report
    cat > /root/firewall-setup-report.txt << EOF
Firewall Setup Report
Generated: $(date)

Configuration:
- Firewall Type: $FIREWALL_TYPE
- SSH Port: $SSH_PORT
- Allowed IPs: $(wc -l < "$ALLOWED_IPS_FILE")
- Blocked IPs: $(wc -l < "$BLOCKED_IPS_FILE")

Features Enabled:
- Rate limiting for SSH
- Port blocking for common attack vectors
- Fail2ban integration
- Automated monitoring
- IP management scripts

Management Commands:
- Allow IP: /usr/local/bin/allow-ip.sh <IP> [COMMENT]
- Block IP: /usr/local/bin/block-ip.sh <IP> [REASON]
- View logs: /var/log/firewall-monitor.log

Important Files:
- Allowed IPs: $ALLOWED_IPS_FILE
- Blocked IPs: $BLOCKED_IPS_FILE
- Firewall Rules: /etc/iptables/rules.v4 (if using iptables)
- Fail2ban Config: /etc/fail2ban/jail.local

Next Steps:
1. Test SSH access on port $SSH_PORT
2. Review allowed/blocked IP lists
3. Configure email notifications for fail2ban
4. Set up log rotation for firewall logs
5. Schedule regular security audits
EOF

    log "Firewall configuration completed successfully!"
    log "Report saved to: /root/firewall-setup-report.txt"

    echo ""
    echo -e "${GREEN}===========================================${NC}"
    echo -e "${GREEN}  FIREWALL CONFIGURATION COMPLETED!${NC}"
    echo -e "${GREEN}===========================================${NC}"
    echo ""
    echo -e "${BLUE}Configuration:${NC}"
    echo "• Firewall: $FIREWALL_TYPE"
    echo "• SSH Port: $SSH_PORT"
    echo "• Monitoring: Enabled"
    echo ""
    echo -e "${BLUE}Management Scripts:${NC}"
    echo "• Allow IP: /usr/local/bin/allow-ip.sh"
    echo "• Block IP: /usr/local/bin/block-ip.sh"
    echo ""
}

# Run main function
main "$@"